version: "3.8"
services:
  postgres:
    image: postgres:12.3
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres: {}
